kody/mssqlProject/Controllers/BudgetController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using mssqlProject.Models;

namespace mssqlProject.Web.Controllers
{
    public class BudgetController : Controller
    {
        private static readonly HttpClient _HttpClient = new HttpClient();

        [HttpGet]
        public IActionResult ShowGrid(string SortOrder, string CurrentSort)
        {
            var response = _HttpClient.GetAsync("https://localhost:44304/api/Budget").Result;
            if(response.IsSuccessStatusCode)
            {

                SortOrder = String.IsNullOrEmpty(SortOrder) ? "Id" : SortOrder;
                ViewBag.CurrentSort = SortOrder;
                var budgets = response.Content.ReadFromJsonAsync<List<Budget>>().Result;

                if (budgets == null)
                    return View();

                switch (SortOrder)
                {
                    case "Id":
                        if (SortOrder.Equals(CurrentSort))
                        {
                            ViewBag.CurrentSort = "";
                            budgets = budgets.OrderByDescending(m => m.Id).ToList();
                        }
                        else
                            budgets = budgets.OrderBy(m => m.Id).ToList();
                        break;
                    case "TripId":
                        if (SortOrder.Equals(CurrentSort))
                        {
                            ViewBag.CurrentSort = "";
                            budgets = budgets.OrderByDescending(m => m.TripId).ToList();
                        }
                        else
                            budgets = budgets.OrderBy(m => m.TripId).ToList();
                        break;
                    case "BankAccunt":
                        if (SortOrder.Equals(CurrentSort))
                        {
                            ViewBag.CurrentSort = "";
                            budgets = budgets.OrderByDescending(m => m.BankAccunt).ToList();
                        }
                        else
                            budgets = budgets.OrderBy(m => m.BankAccunt).ToList();
                        break;
                    case "ShareHoldersCount":
                        if (SortOrder.Equals(CurrentSort))
                        {
                            ViewBag.CurrentSort = "";
                            budgets = budgets.OrderByDescending(m => m.ShareHoldersCount).ToList();
                        }
                        else
                            budgets = budgets.OrderBy(m => m.ShareHoldersCount).ToList();
                        break;
                    case "BudgetSize":
                        if (SortOrder.Equals(CurrentSort))
                        {
                            ViewBag.CurrentSort = "";
                            budgets = budgets.OrderByDescending(m => m.BudgetSize).ToList();
                        }
                        else
                            budgets = budgets.OrderBy(m => m.BudgetSize).ToList();
                        break;
                    default:
                        budgets = budgets.OrderBy(m => m.Id).ToList();
                        break;
                }

                return View(budgets);
            }
            else
            {
                return View();
            }
        }



        [HttpPost]
        public IActionResult FilterShowGrid(int minSH, int maSH, double inBS, double maxBS)
        {
            return View("ShowGrid");
        }

    }
}

kody/mssqlProject/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace mssqlProject.Web.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

kody/mssqlProject/Views/Budget/ShowGrid.cshtml
@model List<Budget>
@{

    int minSH = Model[0].ShareHoldersCount;
    int maxSH = Model[0].ShareHoldersCount;
    double minBS = Model[0].BudgetSize;
    double maxBS = Model[0].BudgetSize;
    foreach(var el in Model)
    {
        if(el.BudgetSize > minBS)
            minBS = el.BudgetSize;
            
        if(el.BudgetSize < minBS)
            minBS = el.BudgetSize;

        if(el.ShareHoldersCount > maxSH)
            maxSH = el.ShareHoldersCount;
            
        if(el.ShareHoldersCount < minSH)
            minSH = el.ShareHoldersCount;
    }

}


@using (Html.BeginForm())   
{  
    <br><br>
    //Formularz filtrowania:
    <form action="ShowGrid" method="get">
    <table>
        <tr>
            <label for="minSH">Liczba członków składających się do budżetu: Min  </label>
            <input type="text" value="@minSH" name="minSH"/><br><br>
        </tr>
        <tr>
            <label for="maxSH">Liczba członków składających się do budżetu: Max  </label>
            <input type="text" value="@maxSH" name="maxSH"/><br><br>
        </tr>
        <tr>
            <label for="minBS">Rozmiar budżetu: Min  </label>
            <input type="text" value="@minBS" name="minBS"/><br><br>
        </tr>
        <tr>
            <label for="maxBS">Rozmiar budżetu: Max  </label>
            <input type="text" value="@maxBS" name="maxBS"/><br><br>
        </tr>
        <tr>
            <td colspan="2"><input type="submit" value="Filtruj" /></td>
        </tr>
    </table>
</form>

<br><br><br><br>



    <div class="grid">  
        <br />  
        <div style="width:90%; margin:0 auto;">  
            <table id="grid" class="table table-striped table-bordered dt-responsive nowrap" width="100%" cellpadding="10" cellspacing="0">  
                <thead>
                    <tr>
                        <th>@Html.ActionLink("Id", "ShowGrid", new { sortOrder = "Id", CurrentSort = ViewBag.CurrentSort })</th>
                        <th>@Html.ActionLink("TripId", "ShowGrid", new { sortOrder = "TripId", CurrentSort = ViewBag.CurrentSort })</th>
                        <th>@Html.ActionLink("BankAccunt", "ShowGrid", new { sortOrder = "BankAccunt", CurrentSort = ViewBag.CurrentSort })</th>
                        <th>@Html.ActionLink("ShareHoldersCount", "ShowGrid", new { sortOrder = "ShareHoldersCount", CurrentSort = ViewBag.CurrentSort })</th>
                        <th>@Html.ActionLink("BudgetSize", "ShowGrid", new { sortOrder = "BudgetSize", CurrentSort = ViewBag.CurrentSort })</th>  
                    </tr>  
                </thead>
                 <tbody>
                        @foreach (var asset in Model)
                        {
                            <tr>
                                <td>@asset.Id</td>
                                <td>@asset.TripId</td>
                                <td>@asset.BankAccunt</td> 
                                <td>@asset.ShareHoldersCount</td> 
                                <td>@asset.BudgetSize</td>
                            </tr>
                        }
                 </tbody>
            </table>
        </div>  
    </div>  
}

kody/mssqlProject/Views/Home/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}



@Html.ActionLink("Idź do strony z tabelą budżetów", "ShowGrid", "Budget");

kody/mssqlProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - mssqlProject</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/mssqlProject.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">mssqlProject</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - mssqlProject - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>